name: Deploy to Tomcat

on:
  push:
    branches:
      - master  # Run the workflow on pushes to the master branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 21  # Setting up JDK 21
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'  # You can choose other JDK distributions (adopt, zulu, etc.)
        java-version: '21'  # Use JDK 21

    - name: Set environment variable for Azure Storage
      run: echo "AZURE_STORAGE_CONNECTION_STRING=${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}" >> $GITHUB_ENV

    - name: Build with Maven
      run: mvn clean install

    - name: Deploy to Tomcat
      run: mvn tomcat7:deploy
      env:
        AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}  # Use the secret in Maven deploy step
